---
title: "Geographical Ecology"
author: "Z620: Quantitative Biodiversity, Indiana University"
date: "February 13, 2015"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## 1.) SETUP
### A. Retrieve and Set Your Working Directory

```{r, results = 'hide'}
rm(list=ls())
getwd()
setwd("~/GitHub/Dimensions/Aim3/papers/DD")
```

### B. Load Packages 

We will use the `vegan` package for biodiversity estimators and related functions.

```{r, results = 'hide', message = FALSE, warning = FALSE} 
require("vegan")
require("sp")          # Classes and methods for handling spatial data
require("geoR")        # Methods for geostatistical analyses
require("rgdal")       # Geospatial Data Abstraction Library
require("raster")      # Methods to create a RasterLayer object
require("maptools")    # Tools for manipulating and reading geospatial data

require("sp")          # Classes and methods for handling spatial data
require("geoR")        # Methods for geostatistical analyses
require("rgdal")       # Geospatial Data Abstraction Library
require("raster")      # Methods to create a RasterLayer object
require("maptools")    # Tools for manipulating and reading geospatial data

require("picante")
require("ape")
require("seqinr")
require("fossil")
require("simba")
require("reshape")
require(reshape)
```

### C. Load Data

```{r, results = 'hide', message = FALSE, warning = FALSE} 
ponds <- read.table("~/GitHub/Dimensions/Aim3/DATA/EnvData/20130801_PondDataMod.csv", sep = ",", header = TRUE)

ponds <- subset(ponds, chla < 2000)
ponds <- subset(ponds, pH > 1)
ponds <- subset(ponds, Salinity > 0.0)
ponds <- subset(ponds, TDS < 5.0)

lats <- as.numeric(ponds[, 3]) # latitudes (north and south)
lons <- as.numeric(ponds[, 4]) # longitudes (east and west)

# Geographic Distances (Kilometers) Among Ponds
long.lat <- as.matrix(cbind(lons, lats))
coord.dist <- earth.dist(long.lat, dist = TRUE)
#coord.dist <- log10(coord.dist)
coord.dist[which(!is.finite(coord.dist))] = NA
coord.dist.ls <- liste(coord.dist, entry = "geo.dist")

#env <- subset(ponds, select=c(Depth:DON))
#env.names <- names(env)
#env.dist <- vegdist(env, "manhattan")

salinity <- as.numeric(env$"Salinity")
spc <- as.numeric(env$"SpC")
tds <- as.numeric(env$"TDS")
doc <- as.numeric(env$"DOC")
env.dist <- vegdist(cbind(salinity, spc, tds, doc), "manhattan")

# transform all distance matrices into list format:
env.dist.ls <- liste(env.dist, entry="env")

df <- data.frame(coord.dist.ls, env.dist.ls[,3])
names(df)[3:4] <- c("geo", "env")
attach(df) #df <- subset(df, struc != 0)

# plot the DDR

par(mfrow=c(1, 1))
plot(df$geo, log10(df$env), xlab="log10(geographic distance)", ylab="log10(environmental distance)", main = "Distance-Decay for the Environment", col='SteelBlue')

OLS <- lm(log10(df$env) ~ df$geo)
OLS # print regression results to the screen
abline(OLS, col="red4")

summary(OLS)
```
