---
title: "Making a Tree Using RAxML"
author: "Jay T. Lennon and William Shoemaker"
date: "June 20, 2017"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## 1) SETUP

### A. Retrieve and Set Your Working Directory

```{r, results = 'hide'}
rm(list = ls())
getwd()
setwd("~/GitHub/Dimensions/Aim1/phylo")
```

### B. Load Packages 

The `require()` function in `R` returns `TRUE` if the package was successfully loaded or `FALSE` if the package failed to load. 
This `for` loop loads each package and installs the package when `require()` returns `FALSE`.

```{r, results = 'hide', message = FALSE, warning = FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=60)} 
package.list <- c('ape', 'seqinr', 'phylobase', 'adephylo', 'geiger', 'picante', 'stats', 'RColorBrewer', 'caper', 'phylolm', 'pmc', 'ggplot2', 'tidyr', 'dplyr', 'phangorn', 'pander') 
for (package in package.list) {
  if (!require(package, character.only=TRUE, quietly=TRUE)) {
    install.packages(package)
    library(package, character.only=TRUE)
  }
}
```

## 2) MAKE TREE
```{r, tidy=TRUE, tidy.opts=list(width.cutoff=60)}
ml.bootstrap <- read.tree("RAxML_bipartitionsBranchLabels.T15")
par(mar = c(1,1,2,1) + 0.1)
plot.phylo(ml.bootstrap, type = "phylogram", direction = "right", show.tip.label=TRUE,
           use.edge.length = FALSE, cex = 0.6, label.offset = 1, main = "Maximum Likelihood with Support Values")
add.scale.bar(cex = 0.7)
nodelabels(ml.bootstrap$node.label, font = 2, bg = "white", frame = "r", cex = 0.5)
```

## 3) LOAD TRAIT DATABASE
```{r}

phy.traits <- read.table("traits.txt", sep = "\t", header = TRUE, row.names = 1)
bet.hedge <- read.table("../data/bet.hedge.table.txt", sep ="\t", header = TRUE)
long.traits.full <- read.csv("../data/weibull_results.csv", sep =",", header = TRUE)
long.traits <- aggregate(long.traits.full[,4:6], by = list(long.traits.full$strain), mean)

```