---
title: "Supplemental Figures: Paired compositional similarity vs. Environment"
geometry: margin=2.54cm
date: "November 7, 2015"
output: pdf_document
header-includes: \usepackage{array}
---


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Retrieve and set the working directory
rm(list=ls())
getwd()
setwd("~/GitHub/Dimensions/Aim3/papers/Paired")
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Load packages
require("picante")
require("ape")
require("vegan") # biodiversity estimators and related functions
require("fossil")
require("simba")
require("reshape")
require(reshape)
require(IDPmisc)
source("~/GitHub/Dimensions/Aim3/bin/MothurTools.R")
source("~/GitHub/Dimensions/Aim3/bin/metrics.R")
load(file = "~/GitHub/Dimensions/Aim3/Mothur/INPond_Initial.RData")
```


```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Load Environmental and Geographical Data
env <- read.table("~/GitHub/Dimensions/Aim3/DATA/EnvData/20130801_PondDataMod.csv", sep = ",", header = TRUE)

env <- subset(env, chla < 2000)
env <- subset(env, pH > 1)
env <- subset(env, Salinity > 0.0)
env <- subset(env, TDS < 5.0)

env.dat <- as.matrix(subset(env, select = Diameter:DON))

# Select DNA Data: Use the `grep()` Command and Rename with `gsub()`
# The active portion, based on cDNA 
active.comm <- Pond97[grep("*-cDNA", rownames(Pond97)), ]
rownames(active.comm) <- gsub("\\-cDNA", "", rownames(active.comm))
rownames(active.comm) <- gsub("\\_", "", rownames(active.comm))

# The community without respect to active or not, 16S rRNA gene sequences
all.comm <- Pond97[grep("*-DNA", rownames(Pond97)), ]
rownames(all.comm) <- gsub("\\-DNA", "", rownames(all.comm))
rownames(all.comm) <- gsub("\\_", "", rownames(all.comm))

# Remove Sites Not in the Environmental Data Set
active.comm <- active.comm[rownames(active.comm)  %in% env$Sample_ID, ]
all.comm <- all.comm[rownames(all.comm)  %in% env$Sample_ID, ]

# Remove Zero-Occurrence Taxa 
#active.comm <- active.comm[ , colSums(active.comm) > 0]
#all.comm <- all.comm[ , colSums(all.comm) > 0]
```


```{r, results = "hide"}
# Get Dominant members
cutoff <- 100

all.sub.comm <- all.comm[, 1:cutoff]
active.sub.comm <- active.comm[, 1:cutoff]

#all.sub.comm <- all.comm
#active.sub.comm <- active.comm

# Define Environmental Matrix
env.chem <- env.dat

# Conduct CCA 
active.cca <- vegan::cca(active.sub.comm ~ env.chem)

# Permutation Tests
anova(active.cca, by = "axis")
cca.fit <- envfit(active.cca, env.chem, perm = 999)

# Calculate Explained Variation
cca.explainvar1 <- round(active.cca$CCA$eig[1] / 
                         sum(c(active.cca$CCA$eig, active.cca$CA$eig)), 3) * 100
cca.explainvar2 <- round(active.cca$CCA$eig[2] / 
                         sum(c(active.cca$CCA$eig, active.cca$CA$eig)), 3) * 100
```


```{r, results = "hide"}
cca.scores <- scores(active.cca)
cca.sites <- as.data.frame(scores(cca.scores$sites))
cca1.scores <- as.matrix(subset(cca.sites, select = CCA1))
env$cca1 <- cca1.scores
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=6}

metric <- "jaccard"
#metric <- "bray"
#metric <- "horn"


dists <- c()
numr <- nrow(all.comm)
i <- 1

while(i <= numr){
  pair <- rbind(all.comm[i,], active.comm[i,])
  dist <- 1 - vegdist(pair, method=metric, binary=FALSE)    
  dists <- c(dists, dist)
  i <- i+1
  }

env$paired.jaccard <- dists
print(mean(dists))
print(median(dists))
```



```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE, fig.width=6, fig.height=6}

metric <- "Jaccard"
env.par <- "CCA1"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$cca1, env$paired.jaccard, main=metric)
lm.out = lm(paired.jaccard ~ cca1, data=env)
abline(lm.out, col="red")
dev.off()


metric <- "Jaccard"
env.par <- "Cal_Volume"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$Cal_Volume, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ Cal_Volume, data=env)
abline(lm.out, col="red")
dev.off()


metric <- "Jaccard"
env.par <- "Depth"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$Depth, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ Depth, data=env)
abline(lm.out, col="red")
dev.off()

metric <- "Jaccard"
env.par <- "SpC"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$SpC, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ SpC, data=env)
abline(lm.out, col="red")

dev.off()


metric <- "Jaccard"
env.par <- "TDS"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$TDS, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ TDS, data=env)
abline(lm.out, col="red")
dev.off()


metric <- "Jaccard"
env.par <- "ORP"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$ORP, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ ORP, data=env)
abline(lm.out, col="red")
dev.off()


metric <- "Jaccard"
env.par <- "Temp"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))
plot(env$Temp, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ Temp, data=env)
abline(lm.out, col="red")
dev.off()


metric <- "Jaccard"
env.par <- "DO"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$DO, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ DO, data=env)
abline(lm.out, col="red")
dev.off()


metric <- "Jaccard"
env.par <- "Salinity"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$Salinity, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ Salinity, data=env)
abline(lm.out, col="red")
dev.off()


metric <- "Jaccard"
env.par <- "pH"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$pH, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ pH, data=env)
abline(lm.out, col="red")
dev.off()


metric <- "Jaccard"
env.par <- "Color"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(env$Color, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ Color, data=env)
abline(lm.out, col="red")
dev.off()

metric <- "Jaccard"
env.par <- "log(chla)"
file <- paste("~/GitHub/Dimensions/Aim3/papers/Paired/figs/", metric,"_",env.par,".png", sep="")
png(filename=file)
  
plot.new()
par(mfrow=c(1, 1))

plot(log(env$chla), env$paired.jaccard)
lm.out = lm(paired.jaccard ~ log(chla), data=env)
abline(lm.out, col="red")
dev.off()

plot(env$DOC, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ DOC, data=env)
abline(lm.out, col="red")

plot(env$DON, env$paired.jaccard)
lm.out = lm(paired.jaccard ~ DON, data=env)
abline(lm.out, col="red")
```

