---
title: "Supplemental Figures: Compositional similarity vs. Geographic distance"
geometry: margin=2.54cm
date: "November 7, 2015"
output: pdf_document
header-includes: \usepackage{array}
---

```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
# Retrieve and set the working directory
rm(list=ls())
getwd()
setwd("~/GitHub/Dimensions/Aim3/papers/DD")

# Load packages
require("sp")          # Classes and methods for handling spatial data
require("geoR")        # Methods for geostatistical analyses
require("rgdal")       # Geospatial Data Abstraction Library
require("raster")      # Methods to create a RasterLayer object
require("maptools")    # Tools for manipulating and reading geospatial data

require("picante")
require("ape")
require("seqinr")
require("vegan") # biodiversity estimators and related functions
require("fossil")
require("simba")
require("reshape")
```

```{r, results = 'hide', echo=FALSE, message = FALSE, warning = FALSE}
env.all <- read.table("~/GitHub/Dimensions/Aim3/DATA/EnvData/20130801_PondDataMod.csv", sep = ",", header = TRUE)

env.filt <- subset(env.all, chla < 2000)
env.filt <- subset(env.filt, pH > 1)
env.filt <- subset(env.filt, Salinity > 0.0)
env.filt <- subset(env.filt, TDS < 5.0)

results.df <- data.frame()
row.num <- nrow(env.filt)
metrics <- c('manhattan', 'euclidean', 'gower', 'mahalanobis')

SampleSize <- c(4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 47)
#SampleSize <- c(4, 16, 12, 16)

for(metric in metrics){
  RS <- c()
  PVALS <- c()
  for(n in SampleSize){
  
    rs <- c()
    pvals <- c()
  
    ct <- 0
    while(ct < 100){
  
      ponds <- sample(1:row.num, n, replace = FALSE)
      env <- env.filt[ponds, ]
  
      lats <- as.numeric(env[, 3]) # latitudes (north and south)
      lons <- as.numeric(env[, 4]) # longitudes (east and west)

      # Geographic Distances (Kilometers) Among Ponds
      long.lat <- as.matrix(cbind(env$long, env$lat))
      coord.dist <- earth.dist(long.lat, dist = TRUE)
      #coord.dist <- log(coord.dist)
      coord.dist[which(!is.finite(coord.dist))] = NA
      coord.dist.ls <- liste(coord.dist, entry = "geo.dist")

      #env <- subset(ponds, select=c(Depth:DON))
      #env.names <- names(env)
      #env.dist <- vegdist(env, "manhattan")

      salinity <- as.numeric(env$"Salinity")
      spc <- as.numeric(env$"SpC")
      tds <- as.numeric(env$"TDS")
      doc <- as.numeric(env$"DOC")
      env.dist <- vegdist(cbind(salinity, spc, tds, doc), metric)

      # transform all distance matrices into list format:
      env.dist.ls <- liste(env.dist, entry="env")

      df <- data.frame(coord.dist.ls, env.dist.ls[,3])
      names(df)[3:4] <- c("geo", "env")
      attach(df) #df <- subset(df, struc != 0)

      r <- cor(log10(df$env), df$geo)
      p <- cor.test(log10(df$env), df$geo)$p.value
  
      rs <- c(rs, r)
      pvals <- c(pvals, p)
      ct <- ct + 1
      }
  
    RS <- c(RS, mean(rs))
    PVALS <- c(PVALS, mean(pvals))
    }
  
  if(metric == 'manhattan'){
    results.df <- cbind(RS, PVALS)
  }else{
    results.df <- cbind(results.df, RS, PVALS)
  }
  }

cols <- c("man_cor", "man_p", "euc_cor", "euc_p", 
          "gow_cor", "gow_p", "mah_cor", "mah_p")
colnames(results.df) <- cols
```


```{r, results = 'hide', message = FALSE, warning = FALSE} 
plot.new()

results2.df <- results.df
results2.df <- na.omit(results2.df)
n <- (SampleSize*(SampleSize-1))/2.0

par(mfrow=c(1, 2))

plot(n, results2.df[,2], xlab="sample size", ylab="p-val", 
     main = "Significance vs. Sample size", col='SteelBlue',
     ylim = c(0, 0.7))

points(n, results2.df[,4], col='red4')
points(n, results2.df[,6], col='purple')
#points(n, results2.df[,8], col='green')

abline(0.05, 0.0, col='grey60')


plot(n, results2.df[,1], xlab="sample size", ylab="R", 
     main = "R vs. Sample size", col='SteelBlue',
     ylim = c(0, 0.4))

points(n, results2.df[,3], col='red4')
points(n, results2.df[,5], col='purple')
#points(n, results2.df[,7], col='green')

abline(0.05, 0.0, col='grey60')
```
